name:                PROJECTNAME
version:             0.1.0.0
github:              "GITHUB_USERNAME/PROJECTNAME"
author:              "AUTHOR_NAME"
maintainer:          "AUTHOR_EMAIL"
copyright:           "COPYRIGHT"

description:         Please see the README on GitHub at <https://github.com/GITHUB_USERNAME/PROJECTNAME#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -foptimal-applicative-do

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- fused-effects
- optparse-applicative
- text

library:
  source-dirs: src

executables:
  PROJECTNAME-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PROJECTNAME

tests:
  PROJECTNAME-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PROJECTNAME
    - base
    - hspec
    - QuickCheck
    - text
